version: '3.8'

services:
  app:
    # This will be replaced by the actual image name from GHCR in the workflow
    image: ghcr.io/${{ github.repository_owner }}/plan-maestro-spotmet:latest
    container_name: spotmet-app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    networks:
      - gateway

networks:
  gateway:
    external: true
